name: F4 Firmware

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: install toolchain
      run: |
        sudo add-apt-repository -y -u ppa:team-gcc-arm-embedded/ppa
        sudo apt -y install gcc-arm-embedded
    - name: check toolchain
      run: arm-none-eabi-gcc --version
    - name: make
      run: make BOARD=REVO -j4 -l4
